function antInfo = info_antenna(antType)

if ischar(antType)
    antType = {antType};
end
antInfo = [];
for idx=1:numel(antType)
    switch antType{idx}
        case 'OVRO'
            antInfo = [antInfo struct(...
                'priRadius',520.0,...
                'secRadius',30.5,...
                'taperRadius',686.0,...
                'taperType','Bessel')];
        case 'BIMA'
            antInfo = [antInfo struct(...
                'priRadius',305.0,...
                'secRadius',30.5,...
                'taperRadius',402.0,...
                'taperType','Bessel')];
        case 'SZA'
            antInfo = [antInfo struct(...
                'priRadius',175.0,...
                'secRadius',17.5,...
                'taperRadius',218.0,...
                'taperType','Bessel')];
        case 'SMA'
            antInfo = [antInfo struct(...
                'priRadius',300.0,...
                'secRadius',17.5,...
                'taperRadius',391.0,...
                'taperType','Bessel')];
        case 'ALMA'
            antInfo = [antInfo struct(...
                'priRadius',600.0,...
                'secRadius',37.5,...
                'taperRadius',465.6,...
                'taperType','Gaussian')];
        case 'ACA'
            antInfo = [antInfo struct(...
                'priRadius',350.0,...
                'secRadius',37.5,...
                'taperRadius',271.6,...
                'taperType','Gaussian')];
        case 'ATA'
            antInfo = [antInfo struct(...
                'priRadius',305.0,...
                'secRadius',0.0,...
                'taperRadius',232.8,...
                'taperType','Gaussian')];
        case 'VLA'
            antInfo = [antInfo struct(...
                'priRadius',1250.0,...
                'secRadius',115.0,...
                'taperRadius',1245,...
                'taperType','Uniform')];
        case 'ngVLA'
            antInfo = [antInfo struct(...
                'priRadius',900.0,...
                'secRadius',0,...
                'taperRadius',493.8,...
                'taperType','Gaussian')];
        case 'sdVLA'
            antInfo = [antInfo struct(...
                'priRadius',2000.0,...
                'secRadius',0,...
                'taperRadius',2300,...
                'taperType','Bessel')];
        case 'CoGS'
            antInfo = [antInfo struct(...
                'priRadius',6.0*50.0,...
                'secRadius',0.0,...
                'taperRadius',6.0*62.3,...
                'taperType','Bessel')];
        case 'YTLA'
            antInfo = [antInfo struct(...
                'priRadius',60.0,...
                'secRadius',19.0,...
                'taperRadius',45.4335,...    % = priRadius * sqrt(20*log(2)/(Te*log(10))); Te: edge taper in dB, positive
                'taperType','Gaussian')];
    end
end

end
